---
title: "Figure 2 Consensus Clustering"
output: html_document
---
## Consensus clustering
Generate alteration matrix with canonical drivers as features
```{r}
combined.alterations <- read.table("primary alteration.txt", sep = "\t", check.names = FALSE, header = TRUE)
canonical.drivers <- c("PIK3CA", "ETV1", "MYC", "LRP1B", "SHQ1", "CHD1", "MAP3K7", "NKX3-1", "PTEN", "CDKN1B", "RB1", "USP10", "TP53", "HDAC5", "BCL2", "ERG", "PPARA")
index <- match(canonical.drivers, rownames(combined.alterations))
driver.alterations <- combined.alterations[index,]
```
Compute coverage
```{r}
altered <- 0
unaltered <- 0
for (i in 2:ncol(driver.alterations)){
  if(sum(driver.alterations[,i]) > 0) {altered <- altered + 1}
  if(sum(driver.alterations[,i]) == 0) {unaltered <- unaltered + 1}
}
paste("Fraction altered is", round(altered/(altered+unaltered), 2))
paste("Fraction unaltered is", round(unaltered/(altered+unaltered), 2))
```
Format matrix and Compute consensus clustering
```{r}
library(ConsensusClusterPlus)
input <- driver.alterations
rownames(input) <- rownames(driver.alterations)
input <- input[,-1]
input <- as.matrix(input)
input[input > 0] <- 1
CCP = ConsensusClusterPlus(input,maxK=6,reps=2000,pItem=1,pFeature=1,clusterAlg="km",distance="euclidean")
```